config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :welcome

  resources :points do
    member do
      get 'streetview'
    end
  end

  get '/current/:lat/:lng' => 'points#current', :as => 'current', :lat => /\d+(\.\d+)?/, :lng => /\d+(\.\d+)?/
  get '/coords/:lat/:lng' => 'points#coord', :as => 'coords', :lat => /\d+(\.\d+)?/, :lng => /\d+(\.\d+)?/

  get '/cache/all' => 'admin#cache_content'

  get '/auth/:provider/callback' => 'sessions#create'
  get '/logout' => 'sessions#destroy', :as => 'logout'
  get '/login' => 'sessions#index', :as => 'login'

  get '/cron' => proc { |env| [200, {'Content-Type' => 'text/plain'}, ['OK']] }

  root :to => 'points#index'
end

app/models/point.rb
class Point < ActiveRecord::Base
  belongs_to :user

 # attr_accessible :name, :latitude, :longitude, :privacy_flag


  scope :ordered, -> { order(:name) }
  scope :published, -> { where(:privacy_flag => true) }

  def self.forecast_cache_key(point)
    "Forecast:#{point.latitude}:#{point.longitude}"
  end

  def self.sunrise_cache_key(point)
    "Sunrise:#{point.latitude}:#{point.longitude}"
  end

  def forecast
    cache_key = Point.forecast_cache_key(self)

    forecast = Rails.cache.read(cache_key)

    if forecast.nil?
      Rails.logger.debug "No cache hit for #{cache_key} - retriving"

      refresh

      forecast = Rails.cache.read(cache_key)
    end

    forecast
  end

  def sunrise
    cache_key = Point.sunrise_cache_key(self)

    sunrise = Rails.cache.read(cache_key)

    if sunrise.nil?
      Rails.logger.debug "No cache hit for #{cache_key} - retriving"

      refresh

      sunrise = Rails.cache.read(cache_key)
    end

    sunrise
  end

  def refresh
    forecast_cache_key = Point.forecast_cache_key(self)

    forecast = LocationForecast.new(self.latitude, self.longitude)

    forecast = forecast.forecast_data

    Rails.cache.write(forecast_cache_key, forecast)

    from = Date.parse(forecast.first['from'])

    to = from + 2

    sunrise = Sunrise.new(self.latitude, self.longitude, from, to)

    times = sunrise.times

    sunrise_cache_key = Point.sunrise_cache_key(self)

    Rails.cache.write(sunrise_cache_key, times)
  end

  def self.cache_content
    Point.all.map do |point|
      data = Hash.new
      data[:point] = point
      data[:cover] = Rails.cache.read(Point.forecast_cache_key(point))
      data[:sunrise] = Rails.cache.read(Point.sunrise_cache_key(point))

      data
    end
  end

  def streetview_url(size)
    params = "location=#{self.latitude},#{self.longitude}&size=#{size}&sensor=false"

    unless ENV['GOOGLE_API_KEY'].blank?
      params = params + "&key=#{ENV['GOOGLE_API_KEY']}"
    end

    "http://maps.googleapis.com/maps/api/streetview?#{params}"
  end

  def location
    "#{self.latitude.round(5)}, #{self.longitude.round(5)}"
  end
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  before_filter :get_points, :except => [:show, :current, :create]
  before_filter :get_point, :only => [:show, :streetview, :update, :destroy]
  before_filter :check_auth, :only => [:new, :create, :update, :destroy]

  def index
  end

  def new
    @point = Point.new
    @point.name = 'New Point'
    @point.privacy_flag = true
  end

  def create
    point = Point.new(point_params)
    point.user = current_user

    point.save

    redirect_to root_url
  end

  def coord
    @point = Point.new
    @point.latitude = params[:lat]
    @point.longitude = params[:lng]
    @point.name = 'Point'
  end

  def update
    @point.update(point_params)

    redirect_to root_url
  end

  def show
  end

  def current
    @point = Point.new

    @point.name = "Latitude #{params[:lat].to_f.round(5)} - Longitude - #{params[:lng].to_f.round(5)}"
    @point.latitude = params[:lat]
    @point.longitude = params[:lng]
    @point.privacy_flag = true
    @point.id = -1
  end

  def streetview
    uri = URI.parse(@point.streetview_url('300x100'))

    http = Net::HTTP.start(uri.host)

    resp = http.head("#{uri.path}?#{uri.query}")

    size = resp['content-length']

    http.finish

    render json: { :available => (size.to_i != 2914), :image => uri.to_s }
  end

  def destroy
    @point.destroy

    redirect_to root_url
  end

  private

  def get_point
    if (current_user)
      @point = Point.includes(:user).where('user_id = ? OR privacy_flag = true', current_user.id).find(params[:id])
    else
      @point = Point.find(params[:id])

      unless @point.privacy_flag
        raise ActiveRecord::RecordNotFound
      end
    end

  end

  def get_points
    if (current_user)
      @points = Point.includes(:user).where('user_id = ? OR privacy_flag = true', current_user.id).ordered
    else
      @points = Point.published.ordered
    end
  end

  def point_params
    params.require(:point).permit(:name, :latitude, :longitude, :privacy_flag)
  end

  def check_auth
    unless current_user
      redirect_to login_url
    end
  end

end

app/views/points/_form.html.haml
= form_for point do |f|
  = f.hidden_field :latitude
  = f.hidden_field :longitude

  .form-group
    = f.label :name, :class => 'control-label'
    = f.text_field :name, :class => 'form-control'

  = f.label :email do
    = f.check_box :privacy_flag, :class => 'form-control'
    Public location?

  .form-group
    %p Move the marker on the map to change the location

  .form-group
    = f.submit 'Save', :class => 'btn btn-primary'
    = link_to 'Delete', point, method: :delete, :class => 'btn btn-danger'

app/views/points/current.html.haml
- content_for :head do
  %script{ :type => 'text/javascript',
           :src => js_map_url }
  = javascript_include_tag 'StyledMarker'

.container-fluid
  .row
    .col-md-3.scrollable
      .point
        %h4
          = link_with_icon('map-marker', @point.name)
        .streetview{ :data => { :streetview => streetview_point_url(@point, :format => :json) }}
    #map.col-md-9{ :data => { :singlepointpath => current_url(:format => :json) }}

app/views/points/index.html.haml
- content_for :head do
  %script{ :type => 'text/javascript',
           :src => js_map_url }
  = javascript_include_tag 'StyledMarker'

.container-fluid
  .row
    .col-md-3.scrollable
      - @points.each do |point|
        .point{ :id => "point_#{point.id}" }
          %h4
            - if point.privacy_flag
              = link_with_icon('map-marker', point.name)
            - else
              = link_with_icon('lock', point.name)
            - if current_user && current_user == point.user
              %span.edit
                = link_to 'Edit', point_path(point)
            %span.coords= point.location
          .streetview{ :data => { :streetview => streetview_point_url(point, :format => :json) }}
    #map.col-md-9{ :data => { :points => points_url(:format => :json) }}

app/views/points/new.html.haml
- content_for :head do
  %script{ :type => 'text/javascript',
           :src => js_map_url }
  = javascript_include_tag 'StyledMarker'

.container-fluid
  .row
    .col-md-3.scrollable
      .point
        = render 'form', :point => @point

    #map.col-md-9{ :data => { :singlepointpath => coords_url(:lat => '59.91199', :lng => '10.75806', :format => :json) }}

app/views/points/show.html.haml
- content_for :head do
  %script{ :type => 'text/javascript',
           :src => js_map_url }
  = javascript_include_tag 'StyledMarker'

.container-fluid
  .row
    .col-md-3.scrollable
      .point
        = form_for @point do |f|
          = f.hidden_field :latitude
          = f.hidden_field :longitude

          .form-group
            = f.label :name, :class => 'control-label'
            = f.text_field :name, :class => 'form-control'

          = f.label :email do
            = f.check_box :privacy_flag, :class => 'form-control'
            Public location?
            
          .form-group
            %p Move the marker on the map to change the location

          .form-group
            = f.submit 'Save', :class => 'btn btn-primary'
            = link_to 'Delete', @point, method: :delete, :class => 'btn btn-danger'

    #map.col-md-9{ :data => { :singlepointpath => point_url(@point, :format => :json) }}