config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :welcome

  resources :points do
    member do
      get 'streetview'
    end
  end

  get '/current/:lat/:lng' => 'points#current', :as => 'current', :lat => /\d+(\.\d+)?/, :lng => /\d+(\.\d+)?/
  get '/coords/:lat/:lng' => 'points#coord', :as => 'coords', :lat => /\d+(\.\d+)?/, :lng => /\d+(\.\d+)?/

  get '/cache/all' => 'admin#cache_content'

  get '/auth/:provider/callback' => 'sessions#create'
  get '/logout' => 'sessions#destroy', :as => 'logout'
  get '/login' => 'sessions#index', :as => 'login'

  get '/cron' => proc { |env| [200, {'Content-Type' => 'text/plain'}, ['OK']] }

  root :to => 'points#index'
end

app/views/layouts/_messages.html.haml
- unless flash.empty?
  .container
    .row
      - flash.each do |name, msg|
        - if msg.is_a? String
          .alert.alert-dismissable{ :class => "alert-#{bootstrap_type(name.to_sym)}" }
            %button.close{ :type => 'button', :'data-dismiss' => 'alert', :'aria-hidden' => 'true' } &times;
            %div{ :id => "flash_#{name}" }= msg

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{ :type => 'button', :data => { :toggle => 'collapse', :target => '.navbar-collapse' } }
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Clouds', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'
      %ul.nav.navbar-nav.pull-right
        = render 'layouts/navigation_links_right'

app/views/layouts/_navigation_links.html.haml
%li#current= link_to 'Current Location', root_path, :data => { :current => current_url(:lat => 0, :lng => 0) }
%li.divider-vertical
  - if current_user
    %li= link_to 'Add Point', new_point_url

app/views/layouts/_navigation_links_right.html.haml
- if current_user
  %li.divider-vertical
  %li.dropdown
    %a.dropdown-toggle{ :href => "#", :data => { :toggle => 'dropdown' } }
      = link_with_icon( 'user', 'Account', true)
      %b.caret
    %ul.dropdown-menu
      %li= link_to 'My Profile', login_path
      %li= link_to 'Log out', logout_path
- else
  %li= link_to 'Log In', login_path
%li.divider-vertical
  %li= link_to 'About', welcome_index_path

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{ :name => 'viewport', :content => 'width=device-width, initial-scale=1.0' }
    %title= (content_for?(:title) ? yield(:title) : 'Clouds')
    %meta{ :name => 'description', :content => (content_for?(:description) ? yield(:description) : 'Cloud Cover') }
    = stylesheet_link_tag('application', media: 'all', 'data-turbolinks-track' => true)
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = yield(:head)
  %body
    %header
      = render 'layouts/navigation'
    %main{ :role => 'main' }
      = render 'layouts/messages'
      = yield